# Generated by Django 3.0.5 on 2020-12-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Priosner',
            fields=[
                ('NIC', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('first_Name', models.CharField(max_length=30)),
                ('last_Name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=999)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=30)),
                ('emergency', models.CharField(max_length=10)),
                ('Assets', models.CharField(max_length=999)),
                ('category', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=None, max_length=30)),
                ('criminalType', models.CharField(choices=[('To be Executed', 'To be Executed'), ('To be Freed', 'To be Freed')], default=None, max_length=30)),
                ('executionType', models.CharField(choices=[('None', 'None'), ('Hanging', 'Hanging'), ('Electrocution', 'Electrocution'), ('Firing', 'Firing'), ('Gas Chamber', 'Gas Chamber'), ('Lethal Injection', 'Lethal Injection')], default=None, max_length=30)),
                ('date', models.DateField()),
            ],
        ),
    ]
