# Generated by Django 3.0.5 on 2020-12-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Priosner',
            new_name='Prisoner',
        ),
    ]
