# Generated by Django 3.0.5 on 2020-12-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackEnd', '0002_auto_20201225_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='prisoner',
            name='crimeDetails',
            field=models.CharField(default='Null', max_length=999),
            preserve_default=False,
        ),
    ]
